name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
      env:
        # ダミーの環境変数を設定し、ビルドエラーを回避する
        VITE_FIREBASE_API_KEY: "dummy"
        VITE_FIREBASE_AUTH_DOMAIN: "dummy"
        VITE_FIREBASE_PROJECT_ID: "dummy"
        VITE_FIREBASE_STORAGE_BUCKET: "dummy"
        VITE_FIREBASE_MESSAGING_SENDER_ID: "dummy"
        VITE_FIREBASE_APP_ID: "dummy"
